services:
  - type: web
    name: ml-model-api
    # env: python
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    autoDeploy: true
